#.streamlit/secrets.toml
[connections.snowflake]
account = "VGBJHIP-HIB81568"
user = "SALONIGIRATKAR"
password = "Giratkar11@2022"
role = "SYSADMIN"
warehouse = "COMPUTE-WH"
database = "SMOOTHIES"
schema = "PUBLIC"
