#.streamlit/secrets.toml
[connections.snowflake]
account = "VGBJHIP-HIB81568"
user = "SALONIGIRATKAR"
password = "Giratkar2@2022"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
